### ISSUE TITLE
Footer Links (Social Media Profiles)

### ISSUE THREAD

**Issue by robinbastien** [norr0065/portfolio-site#7]
For outbound links, it's good to make them open in a new tab so the user doesn't **bounce** (jump off the page to a new URL). It's also good to handle capitalization on the styling side of things instead of capitalizing the text itself. 

You can add the following to make them open in new tab:
`target="_blank"`

This:

``` HTML
<li class="footie"><a href="https://twitter.com/britnor52"> TWITTER</a></li>
```

will become:

``` HTML
<li class="footie capitalize">
  <a href="https://twitter.com/britnor52" target="_blank">Twitter</a>
</li>
```

...Then in your stylesheet, if you don't already have a class that capitalizes, add the following in type.css:

``` CSS
.capitalize { text-transform: uppercase; }
```

**Comment by norr0065** [comment]
Thanks for catching this!
