### ISSUE TITLE
Object classes are on the grid structure

### ISSUE THREAD

**Issue by robinbastien** [norr0065/portfolio-site#9]
To solve the portfolio link falling below the logo on mobile, there's a rule of thumb to follow. Never use object classes for cells. Always make them a child of the cell. By "Object Class", I mean a class in which you name something on the site.

Examples: .nav, .logo, .site-footer, .section--portfolio

On the other hand, it's fine to use classes that style the text within that cell. Here at machine we use stuff like .hand-text-center or .text--uppercase.

You're also using .nav for the parent nav container as well as the nav item! Try to keep these distinguished. You can make it so anything that falls as a descendent of a parent section, add two underscores and write the name of the specific item. Example:

``` HTML
<nav class="nav">
   <ul class="nav__items">
      <li class="nav__item"><a href="#wuddup">Your Link</a></li>
      <li class="nav__item"><a href="#wuddup">Your Link</a></li>
  </ul><!--.nav__items-->
</nav>
```

So here's how you can fix this in the header, keep your eyes peeled for other areas on the site where this can be fixed :)

``` HTML
<!-- Your current header -->
<header>
  <div class="nav-bar grid">
    <div class="logo unit unit-s-1-5 unit-m-1-5 unit-l-1-5">
      <h1 class="wordmark"><a href="/index.html">BRIT NORRIS</a></h1>
    </div>
    <div class="milli nav unit unit-xs-1-2 unit-s-1-2 unit-m-3-5 unit-l-3-5">
      <ul>
        <li class="nav"><a href="/portfolio.html">PORTFOLIO</a></li>
      </ul>
    </div>
  </div>
</header>
```

``` HTML
<!-- Updated -->
<header class="nav-bar">
  <div class="grid"><!-- NOTE: Grid has no other classes -->
    <div class="unit unit-s-1-5 unit-m-1-5 unit-l-1-5"> <!-- NOTE: Cells only have unit classes on it-->
      <div class="logo">
         <h1 class="wordmark uppercase"><a href="/index.html">Brit Norris</a></h1>
      </div><!--.logo-->
    </div><!--.unit-->
    <div class="milli unit unit-xs-1-2 unit-s-1-2 unit-m-3-5 unit-l-3-5">
      <nav class="nav">
        <ul>
          <li class="nav__item uppercase"><a href="/portfolio.html">Portfolio</a></li><!-- NOTE: Use two underscores to easily distinguish items, so you dont accidentally reuse classes. -->
        </ul>
     </nav>
    </div><!--.unit-->
  </div><!--.grid-->
</header><!--.nav-bar-->
```

**Comment by norr0065** [comment]
I want to chat with you about my naming convention at work :) Thx again
